# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3729333aaea0120e3071aad59b6f6ef10762ba818b45636f1a431a780f0f1a6ba451198957df916887bec45d3900055c701a213a4445ac9188efabee5d1efa

test:
  secret_key_base: 012b6f83f109afe4cea6a257a0b40ffcf2767c1eccd5c404fda098d6de5c8495d492232027e3b8e578f36fffce17a6f59d904cdb73427bd1313b70ca4eb73c17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
